export const CLIENT_ONBOARDING_QUESTIONS = [
  {
    id: 'fullName',
    title: 'What is your full name?',
    description: 'Enter your name exactly as you want it used during your job search.',
    type: 'text',
    placeholder: 'Your full name',
    required: true,
  },
  {
    id: 'phone',
    title: 'What is your preferred phone number?',
    description: 'Use the number where you can be reached for important application updates.',
    type: 'tel',
    placeholder: '+1 555 000 0000',
    required: true,
  },
  {
    id: 'currentLocation',
    title: 'Where are you currently located?',
    description: 'Enter your city, state or region, and country.',
    type: 'text',
    placeholder: 'City, State, Country',
    required: true,
  },
  {
    id: 'targetRoles',
    title: 'What roles are you targeting?',
    description: 'You can enter multiple job titles separated by commas.',
    type: 'textarea',
    placeholder: 'Financial Analyst, FP&A Analyst, Budget Analyst',
    required: true,
  },
  {
    id: 'targetIndustries',
    title: 'Which industries are you interested in?',
    description: 'Tell us which industries you would most like to work in.',
    type: 'textarea',
    placeholder: 'Banking, Technology, Healthcare',
    required: true,
  },
  {
    id: 'preferredLocations',
    title: 'Where would you like to work?',
    description: 'List your preferred cities, states, countries, or indicate that you are open.',
    type: 'textarea',
    placeholder: 'New York, Texas, Remote, Open to relocation',
    required: true,
  },
  {
    id: 'workArrangement',
    title: 'What work arrangement do you prefer?',
    description: 'Choose the working arrangement that best matches your preference.',
    type: 'select',
    placeholder: 'Select a work arrangement',
    options: [
      'Remote',
      'Hybrid',
      'On-site',
      'Remote or Hybrid',
      'Hybrid or On-site',
      'Open to all',
    ],
    required: true,
  },
  {
    id: 'employmentType',
    title: 'What type of employment are you looking for?',
    description: 'Choose your preferred employment type.',
    type: 'select',
    placeholder: 'Select an employment type',
    options: [
      'Full-time',
      'Part-time',
      'Contract',
      'Internship',
      'Graduate Program',
      'Open to multiple types',
    ],
    required: true,
  },
  {
    id: 'salaryExpectation',
    title: 'What is your expected salary range?',
    description: 'Enter your preferred salary range and currency.',
    type: 'text',
    placeholder: '$60,000 - $80,000 per year',
    required: true,
  },
  {
    id: 'workAuthorization',
    title: 'What is your current work authorization status?',
    description: 'Tell us where you are currently authorized to work.',
    type: 'textarea',
    placeholder: 'Authorized to work in the United States without restriction',
    required: true,
  },
  {
    id: 'sponsorship',
    title: 'Will you require employment sponsorship?',
    description: 'Select the option that best describes your situation.',
    type: 'select',
    placeholder: 'Select an option',
    options: [
      'No',
      'Yes',
      'Not currently, but may require it in the future',
      'Not sure',
    ],
    required: true,
  },
  {
    id: 'yearsExperience',
    title: 'How many years of relevant experience do you have?',
    description: 'An estimate is fine.',
    type: 'select',
    placeholder: 'Select experience level',
    options: [
      'Less than 1 year',
      '1-2 years',
      '3-4 years',
      '5-7 years',
      '8-10 years',
      'More than 10 years',
    ],
    required: true,
  },
  {
    id: 'linkedinUrl',
    title: 'What is your LinkedIn profile URL?',
    description: 'This helps us review how your professional profile aligns with your applications.',
    type: 'url',
    placeholder: 'https://www.linkedin.com/in/your-profile',
    required: false,
  },
  {
    id: 'portfolioUrl',
    title: 'Do you have a portfolio or professional website?',
    description: 'Add the link if one is relevant to your job search.',
    type: 'url',
    placeholder: 'https://yourportfolio.com',
    required: false,
  },
  {
    id: 'additionalPreferences',
    title: 'Is there anything else we should know about your job search?',
    description: 'Add any preferences, restrictions, priorities, or information that will help us apply more accurately.',
    type: 'textarea',
    placeholder: 'Share any additional information here...',
    required: false,
  },
];

export const CLIENT_ONBOARDING_TOTAL =
  CLIENT_ONBOARDING_QUESTIONS.length;
